### ISSUE TITLE
Problems with the WLAN module

### ISSUE THREAD

**Issue by ghost** [bq/wlan_module_qcom#2]
I'm having problems with the kernel and the WLAN module for Piccolo (M5), is it possible that some route is wrong? I leave a link to Hastebin with the error.

[Hastebin](https://hastebin.com/yulekatuje.go)

**Comment by Kra1o5** [comment]
Hi @LluisR98 ,

Following these instructions compiles correctly: https://github.com/bq/wlan_module_qcom/tree/aquaris-M5

Greetings

**Comment by ghost** [comment]
That's the problem, I'm using the readme commands. Is it possible to make some modification?

**Comment by Kra1o5** [comment]
I'm sorry but I don't understand what you mean

**Comment by ghost** [comment]
We are going to rewind. I am trying to compile a basic version of the M5 kernel but with the WLAN module I have problems. The kernel compiles well and without errors, I have been able to upload it to 3.10.69 but I do not know when WiFi started to fail.

Then I'm doing the process with the WLAN directory, foolish me if I did not start it, but it gives problems. I enclose a [Hastebin](https://hastebin.com/tayosotaho.sql) with the whole process that I do, when there [...] is because of the long process.

**Comment by Kra1o5** [comment]
Hi @LluisR98 ,
Bad checkout: "git checkout aquaris-M5" need to be "git checkout tags/5.2.0_20180228-1304" in both repos.

**Comment by ghost** [comment]
I'm trying the new checkout. The "git checkout tags/5.2.0_20180228-1304" doesn't work but "git checkout tags/5.1.0..." works good (At least that seems). In case it works I tell you and I close it.

**Comment by ghost** [comment]
I have already been able to solve the problem and the compilation works, I am going to close the issue. Thank you!
